apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp
spec:
  ports:
    - name: http
      port: 80
      nodePort: 30080
  selector:
    app: webapp
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue
spec:
  ports:
    - name: admin
      port: 8161
      nodePort: 30010
  selector:
    app: queue
  type: NodePort
